### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by datalogics-bhaugen** [Minitex/ls-ansible-deploy#1]
There does not appear to be a license contained in the repository or mentioned in the README. It would be great to have an explicit license so that those who may want to use this project for administration of Library Simplified know what the licensing is.

For information about choosing a license, you can look at https://choosealicense.com that GitHub created to help with this sort of thing.

**Comment by swandog30** [comment]
Thanks for pointing that out.  Just added an MIT license.

**Comment by datalogics-bhaugen** [comment]
Thanks for taking care of this @swandog30!
